version: 2

project_name: urso

gomod:
  # https://goreleaser.com/customization/verifiable_builds/?h=proxy
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
  # gobinary: go1.25

before:
  hooks:
    - go mod tidy
    - sh ./scripts/completions.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    # ensures mod timestamp to be the commit timestamp
    mod_timestamp: "{{ .CommitTimestamp }}"
    main: ./cmd/urso

source:
  enabled: true
  name_template: "{{ .ProjectName }}.src"

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: false
    builds_info:
      mtime: "{{ .CommitTimestamp }}"
    files:
      - completions/*

sboms:
  - artifacts: archive
  - id: packages
    artifacts: package
  - id: source
    artifacts: source

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      ids:
        - urso
      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{ .Env.MACOS_SIGN_PASSWORD }}"
      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"
        wait: false # Don't wait for it, notarization takes long and pipeline will exceed context deadline

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: "https://urso.run"
    description: "Urso is a GitHub Actions runner manager"
    maintainer: "Petr Vala <petr.m.vala@gmail.com>"
    license: "PolyForm Noncommercial License 1.0.0"
    vendor: "urso.run"
    bindir: /usr/bin
    section: utils
    mtime: "{{ .CommitDate }}"
    contents:
      - src: completions/urso.bash
        dst: /usr/share/bash-completion/completions/urso
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
      - src: completions/urso.fish
        dst: /usr/share/fish/vendor_completions.d/urso.fish
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
      - src: completions/urso.zsh
        dst: /usr/share/zsh/vendor-completions/_urso
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        dst: /usr/share/doc/urso/copyright
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

homebrew_casks:
  - name: urso
    repository:
      owner: urso-run
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_RELEASER_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://urso.run"
    description: "Urso is a GitHub Actions runner manager"
    binaries:
      - urso
    completions:
      bash: completions/urso.bash
      zsh: completions/urso.zsh
      fish: completions/urso.fish

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
