package urso

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"text/template"
)

const (
	vectorServiceName = "com.urso-run.vector"
	vectorConfigTmpl  = `# Vector configuration for Urso
# This file is automatically generated. Manual changes may be overwritten.
sources:
  urso_logs:
    type: file
    include:
      - ${HOME}/.urso/logs/*.log
      {{range .Runners}}
      - ${HOME}/.urso/runners/{{.Name}}/_diag/*.log
      - ${HOME}/.urso/runners/{{.Name}}/_logs/*.log
      {{end}}
    read_from: beginning
    data_dir: ${HOME}/.urso/vector/data

  host:
    type: host_metrics
    scrape_interval_secs: 30
    collectors:
      - host
      - process
      - cpu
      - memory
      - filesystem
    process:
      processes:
        includes:
          - "Runner.Listener"

sinks:
  urso_logs_http:
    type: http
    inputs: [urso_logs]
    uri: https://urso.run/api/machine/{{.MachineID}}/logs
    method: post
    encoding:
      codec: json
    request:
      headers:
        Authorization: "Bearer {{.MachineToken}}"

  urso_metrics_http:
    type: http
    inputs: [host]
    uri: https://urso.run/api/machine/{{.MachineID}}/metrics
    method: post
    encoding:
      codec: json
    request:
      headers:
        Authorization: "Bearer {{.MachineToken}}"
`
)

// VectorObs defines the interface for managing the Vector observability process.
type VectorObs interface {
	Install(ctx context.Context) error
	UpdateConfig(machineID, machineToken string, runners []RunnerConfig) error
	Uninstall(ctx context.Context) error
}

// VectorManager handles the lifecycle and configuration of the Vector observability process.
type VectorManager struct {
	machine  MachineInspector
	sm       ServiceManager
	ursoHome string
	logger   *slog.Logger
}

// NewVectorManager creates a new VectorManager.
func NewVectorManager(m MachineInspector, sm ServiceManager, ursoHome string, logger *slog.Logger) *VectorManager {
	return &VectorManager{
		machine:  m,
		sm:       sm,
		ursoHome: ursoHome,
		logger:   logger,
	}
}

// Install ensures the Vector service is registered with the system.
// This should be called during the 'install' command.
func (v *VectorManager) Install(ctx context.Context) error {
	vectorPath, err := v.machine.LookPath("vector")
	if err != nil {
		v.logger.Info("vector binary not found in PATH, skipping service installation. Please install vector (https://vector.dev) to enable observability.")
		return nil //nolint:nilerr // Returning nil is intentional when vector is missing to avoid failing the whole urso install
	}

	configDir := filepath.Join(v.ursoHome, "vector")
	if err := v.machine.MkdirAll(configDir); err != nil {
		return fmt.Errorf("failed to create vector config directory: %w", err)
	}

	configPath := filepath.Join(configDir, "vector.yaml")

	v.logger.Info("installing vector background service", "path", vectorPath)

	svcCfg := ServiceConfig{
		Name:           vectorServiceName,
		ExecutablePath: vectorPath,
		Arguments:      []string{"-w", "-c", configPath},
		UrsoHome:       v.ursoHome,
	}

	if err := v.sm.Install(ctx, svcCfg); err != nil {
		return fmt.Errorf("failed to install vector service: %w", err)
	}

	return nil
}

// UpdateConfig writes the vector.yaml file based on the current machine ID and runner list.
// Because Vector is started with the '-w' flag, it will automatically reload when this file is updated.
func (v *VectorManager) UpdateConfig(machineID, machineToken string, runners []RunnerConfig) error {
	// Only proceed if vector is present on the system.
	if _, err := v.machine.LookPath("vector"); err != nil {
		v.logger.Debug("skipping vector config update: binary not found")
		return nil //nolint:nilerr // Returning nil is intentional when vector is missing
	}

	configDir := filepath.Join(v.ursoHome, "vector")
	if err := v.machine.MkdirAll(configDir); err != nil {
		return fmt.Errorf("failed to create vector config directory: %w", err)
	}

	dataDir := filepath.Join(configDir, "data")
	if err := v.machine.MkdirAll(dataDir); err != nil {
		return fmt.Errorf("failed to create vector data directory: %w", err)
	}

	configPath := filepath.Join(configDir, "vector.yaml")
	v.logger.Info("updating vector configuration", "path", configPath, "runner_count", len(runners))

	tmpl, err := template.New("vector").Parse(vectorConfigTmpl)
	if err != nil {
		return fmt.Errorf("failed to parse vector template: %w", err)
	}

	f, err := os.OpenFile(configPath, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("failed to open vector config file: %w", err)
	}
	defer f.Close()

	data := struct {
		UrsoHome     string
		MachineID    string
		MachineToken string
		Runners      []RunnerConfig
	}{
		UrsoHome:     v.ursoHome,
		MachineID:    machineID,
		MachineToken: machineToken,
		Runners:      runners,
	}

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to execute vector template: %w", err)
	}

	return nil
}

// Uninstall removes the Vector service and its configuration.
func (v *VectorManager) Uninstall(ctx context.Context) error {
	v.logger.Info("uninstalling vector observability service")

	if err := v.sm.Uninstall(ctx, vectorServiceName); err != nil {
		v.logger.Warn("failed to uninstall vector service", "error", err)
	}

	configDir := filepath.Join(v.ursoHome, "vector")
	if err := v.machine.RemoveAll(configDir); err != nil {
		v.logger.Warn("failed to remove vector config directory", "error", err)
	}

	return nil
}
