rootDir: urso-run

runners:
  - name: first
    group: Default
    url: https://github.com/urso-run
    labels: ["urso-run"]

  - name: second
    group: Default
    url: https://github.com/urso-run
    labels: ["urso-run"]
