on:
  workflow_dispatch:

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing

jobs:
  release:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)
          persist-credentials: false

      - name: Authenticate & Install Cloudsmith CLI (OIDC)
        uses: cloudsmith-io/cloudsmith-cli-action@76c8ff51a34bea1036d9b7708f10a929624a1910 # v2.0.1
        with:
          oidc-namespace: ${{ secrets.CLOUDSMITH_OIDC_NAMESPACE }}
          oidc-service-slug: ${{ secrets.CLOUDSMITH_SERVICE_ACCOUNT }}

      - name: Run subsequent steps
        run: echo "Successfully authenticated with Cloudsmith."
